### PR TITLE
Improve IndieAuth spec compliance

### LINKED ISSUE #54: Improve compliance with IndieAuth spec
Implement IndieAuth client changes detailed in [Aaron's article](https://aaronparecki.com/2020/12/03/1/indieauth-2020), including OAuth 2.0 PKCE (Proof Key for Code Exchange).

### PR DESCRIPTION
**Pull request by barryf**
Closes #54

### CODE REVIEW

**Comment by barryf** [comment]
@jamietanna Does this new version work correctly with your new IndieAuth server? It should support PKCE.

**Comment by jamietanna** [comment]
I'm seeing a fail with `400 received from token endpoint.` on redirect with `code`, so possibly not - I'll have a look my side, is there anything you can check in your logs to see what went wrong?

**Comment by jamietanna** [comment]
Looks like I'm not happy with the PKCE :thinking:

**Comment by jamietanna** [comment]
Looks like the challenge you're sending has Base64 padding `=`s which aren't allowed - you'll need to strip them before you send them, otherwise servers will reject it

**Comment by barryf** [comment]
This is how I construct the `code_challenge` in Ruby. It seems to follow the spec's method, although I may need to do some more reading.

```ruby
code_challenge = Base64.urlsafe_encode64(
  Digest::SHA256.hexdigest(code_verifier)
)
```

**Comment by jamietanna** [comment]
I had this as well on the server side, I think when you compute that, you need to `gsub(/=/, '')`

**Comment by barryf** [comment]
Ah, good spot re: the "=" added. I'll strip them. Thanks :+1:

**Pull request merged**
